### ISSUE TITLE
USER STORY:<TITLE>

### ISSUE THREAD

**Issue by SanitaB17** [SanitaB17/My-First-Agile-Project#4]
**User Story:** In order to automatically hide the poll as an administrator, I can pick the expirity date while publishing the poll

**Acceptance Criteria:**
    **a.** The poll should disappear at 11:59 PM on the target date
    **b.** The real estate of the "Poll" Should be reserved on the home page. a message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
    **c.** The administrator expiry date should be at least 3 days after the current date.

**Tasks:**
 - [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and show the name of the submitter
 - [ ] Create a new field in the model to track the username
 - [ ] Update the controller function
 - [ ] Update unit test scripts
 - [ ] Test the functionality
